using Test_Optinum
using LinearAlgebra
using Test
using Optinum

Test_Optinum.test_Algo_Newton(false,Optinum.Algorithme_De_Newton)
Test_Optinum.test_pas_de_cauchy(false,Optinum.Pas_De_Cauchy)
Test_Optinum.test_regions_de_confiance(false,Optinum.Regions_De_Confiance)
Test_Optinum.test_Lagrangien_Augmente(false,Optinum.Lagrangien_Augmente)

